name: Build with file upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [ packed ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build shell module
        run: ./gradlew shell:build
      - name: Build dpt module
        run: ./gradlew dpt:build
      - name: List files
        run: ls --full-time

      - name: Prepare artifact
        run:  zip -r -q packed.zip ./*
        
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: packed
          path: packed.zip
